defaults:
  - trainer: smoke_test
  - model: default
  - optimizer: adam
  - dataset: random
  - lr_scheduler: reduce_on_plateau

hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${now:%Y-%m-%d-%H-%M}
